services:
  - type: web
    name: gymai-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: PORT
        value: 8000

  - type: web
    name: gymai-frontend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port $PORT --server.address 0.0.0.0
    envVars:
      - key: API_BASE_URL
        value: https://gymai-backend.onrender.com
      - key: PORT
        value: 8501

databases:
  - name: gymai-db
    plan: free
